name: mosaic_example
description: Minimal example for the mosaic package.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mosaic_widgets:
    path: ../
