name: mosaic_cli
description: "Command-line tool to scaffold, generate, and manage native home widgets for the Mosaic framework."
publish_to: none
version: 1.0.0
# TODO: update to the real repo URL
repository: https://github.com/mustafa-707/mosaic-widgets
topics:
  - home-widget
  - cli
  - code-generation
  - widget

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  mosaic_core:
    path: ../core
  mosaic_android:
    path: ../android
  mosaic_ios:
    path: ../ios
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
